name: "Static Code Analysis"

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  Linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Perform static code analysis via golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
